### PR TITLE
Version Bump, build and push modification. 

### PR DESCRIPTION
**Pull request by john-delivuk**
- Encountered a grpc bug around request size. 
- Had some issues building locally, made changes to allow this to work more seamlessly as close to owners original setup.

### CODE REVIEW

**Comment by mhausenblas** [comment]
Thanks a lot for this PR @john-delivuk! I'm currently on travel (KubeCon and next week Red Hat Summit), so please allow me some time to test it before I merge ;)

**Comment by hypery2k** [comment]
@mhausenblas Any news?

**Comment by hypery2k** [comment]
thanks for the fast response. Looking forward for the new version

**Comment by canit00** [comment]
Hate to be that person. Anyway, we can get this PR merged please?

**Comment by mhausenblas** [comment]
Again, @john-delivuk @hypery2k and @canit00 sorry for the delay here and thanks for your patience!

**Pull request merged**
